new workflow for wifi_managed

diff --git a/raumfeld/testsuite/rootfs/tests/wifi_managed b/raumfeld/testsuite/rootfs/tests/wifi_managed
--- a/raumfeld/testsuite/rootfs/tests/wifi_managed
+++ b/raumfeld/testsuite/rootfs/tests/wifi_managed
@@ -6,6 +6,9 @@
 TITLE="WIRELESS-MANAGED"
 DIALOGOPTS="--title $TITLE"
 
+dialog_info "Testing WIRELESS in managed mode. Now scanning for RaumfeldFactoryTest"
+
+
 source ./wifi_managed.inc
 
 ./leds-blink 6 &
@@ -16,9 +19,28 @@ killall dhclient
 
 /sbin/ifconfig ${WIRELESS_IFNAME} down
 /sbin/iwconfig ${WIRELESS_IFNAME} mode Managed
-/sbin/iwconfig ${WIRELESS_IFNAME} essid ${ESSID}
+/sbin/iwconfig ${WIRELESS_IFNAME} essid RaumfeldFactoryTest
 /sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS} up
 /usr/sbin/dhclient -sf /dhclient-script ${WIRELESS_IFNAME}
+
+
+if [ ! -z "$(iwconfig ${WIRELESS_IFNAME} | grep -i Not-Associated)" ]; then
+	err="can't connect to AP RaumfeldFactoryTest"
+  dialog_err "$err"
+  exit 1
+fi
+
+
+QUALITY=$(iwconfig ${WIRELESS_IFNAME} | grep -i "dBm" | cut -f3 -d= | cut -f1 -d' ')
+MIN_QUALITY=-40
+
+if [ ${MIN_QUALITY} -gt ${QUALITY} ]; then
+	err="SIGNAL LEVEL $QUALITY TOO WEAK ($MIN_QUALITY required) -- ESSID $ESSID"
+  dialog_err "$err"
+  exit 1
+fi
+
+
 
 killall leds-blink
 
