usbmount: cleanup
Remove most changes and install a custom usbmount.conf instead.
Also add ext4 as supported filesystem.

diff --git a/package/usbmount/usbmount-0.0.14.1-use-env-instead-of-conf.patch b/package/usbmount/usbmount-0.0.14.1-use-env-instead-of-conf.patch
--- a/package/usbmount/usbmount-0.0.14.1-use-env-instead-of-conf.patch
+++ b/package/usbmount/usbmount-0.0.14.1-use-env-instead-of-conf.patch
@@ -1,32 +1,18 @@
---- usbmount-0.0.14.1/usbmount	2010-01-05 15:04:40.000000000 +0100
-+++ usbmount-0.0.14.1/usbmount-edited	2010-01-05 16:05:29.000000000 +0100
-@@ -40,17 +40,20 @@
+--- usbmount-0.0.14.1-orig/usbmount	2007-01-27 12:22:14.000000000 +0100
++++ usbmount-0.0.14.1/usbmount	2010-08-05 09:12:04.000000000 +0200
+@@ -40,7 +40,6 @@
  test -x /lib/udev/vol_id || { log err "cannnot execute /lib/udev/vol_id"; exit 1; }
  
  # Default values for configuration variables.
 -MOUNTPOINTS=""
--FILESYSTEMS=""
--MOUNTOPTIONS=""
--FS_MOUNTOPTIONS=""
--VERBOSE="no"
-+# MOUNTPOINTS=""
-+# FILESYSTEMS=""
-+# MOUNTOPTIONS=""
-+# FS_MOUNTOPTIONS=""
-+# VERBOSE="no"
+ FILESYSTEMS=""
+ MOUNTOPTIONS=""
+ FS_MOUNTOPTIONS=""
+@@ -57,6 +56,7 @@
+ if test "$1" = add; then
  
- # Read configuration file.
--if test -r /etc/usbmount/usbmount.conf; then
--    . /etc/usbmount/usbmount.conf
--fi
--
-+# if test -r /etc/usbmount/usbmount.conf; then
-+#     . /etc/usbmount/usbmount.conf
-+# fi
-+
-+FILESYSTEMS="ext2 ext3 msdos vfat ntfs hfs hfsplus"
-+MOUNTOPTIONS="ro,noexec,nodev,noatime"
-+LOGFILE="/var/log/usbmount.log"
- 
- umask 022
- 
+     # Acquire lock.
++    mkdir -p /var/run/usbmount/
+     log debug "trying to acquire lock /var/run/usbmount/.mount.lock"
+     lockfile-create --retry 3 /var/run/usbmount/.mount || \
+ 	{ log err "cannot acquire lock /var/run/usbmount/.mount.lock"; exit 1; }
